add_newline = false
format = """$directory$character"""
right_format = """$all"""
command_timeout = 1000

[character]
success_symbol = '[â¯](bold green)'
error_symbol = '[âœ—](bold red)'

# Shows kubernetes context and namespace
# [kubernetes]
# format = 'via [ó±ƒ¾ $context\($namespace\)](bold purple) '
# disabled = false

[directory]
truncation_symbol = 'â€¦/'

[git_status]
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = '[â‡£$\($count\)](red)'
modified = '[!\($count\)](yellow)'
untracked = '[?\($count\)](blue)'
staged = '[+](green)'
format = '([$conflicted$stashed$deleted$renamed$modified$typechanged$untracked$ahead_behind$staged]($style) )'

[git_branch]
format = '[$symbol$branch (:$remote_branch)]($style)'

[aws]
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
disabled = false
style = 'bold blue'
symbol = "îŒ½ "

[golang]
format = '[î˜§ ](bold cyan)'

[kubernetes]
symbol = 'â˜¸ '
disabled = true

[terraform]
format = '[ğŸ¥ $version $workspace]($style) '
